/* Generated by tools/ci18n_compile from en.txt. Do not edit. */

#ifndef CI18N_COMPILED_en_H
#define CI18N_COMPILED_en_H

#include "ci18n.h"

/* Keys, for CI18N_KEY(). */
#ifndef ci18n_key_title
#define ci18n_key_title 1
#endif
#ifndef ci18n_key_greeting
#define ci18n_key_greeting 1
#endif
#ifndef ci18n_key_files
#define ci18n_key_files 1
#endif

#ifdef CI18N_FLASH_STRINGS
typedef char ci18n_en_longest_key_fits[13 <= CI18N_MAX_KEY_LENGTH ? 1 : -1];
typedef char ci18n_en_longest_value_fits[20 <= CI18N_MAX_VALUE_LENGTH ? 1 : -1];
#endif

static const char ci18n_en_strings[] CI18N_ROM = {
    '\164', '\151', '\164', '\154', '\145', '\000', '\143', '\151', '\061', '\070', '\156', '\040',
    '\157', '\156', '\040', '\141', '\156', '\040', '\101', '\162', '\144', '\165', '\151', '\156',
    '\157', '\000', '\147', '\162', '\145', '\145', '\164', '\151', '\156', '\147', '\000', '\110',
    '\145', '\154', '\154', '\157', '\054', '\040', '\173', '\156', '\141', '\155', '\145', '\175',
    '\041', '\000', '\146', '\151', '\154', '\145', '\163', '\133', '\157', '\156', '\145', '\135',
    '\000', '\173', '\143', '\157', '\165', '\156', '\164', '\175', '\040', '\146', '\151', '\154',
    '\145', '\000', '\146', '\151', '\154', '\145', '\163', '\133', '\157', '\164', '\150', '\145',
    '\162', '\135', '\000', '\173', '\143', '\157', '\165', '\156', '\164', '\175', '\040', '\146',
    '\151', '\154', '\145', '\163', '\000',
    0
};

static const uint32_t ci18n_en_entries[] CI18N_ROM = {
    0u, 6u, 2556802313u, 26u, 35u, 3572350902u,
    50u, 61u, 2563599378u, 74u, 87u, 3344852324u,
    0
};

static const uint32_t ci18n_en_slots[] CI18N_ROM = {
    4294967295u, 2556755968u, 2563571714u, 4294967295u, 3572301825u, 3344826371u,
    4294967295u, 4294967295u,
};

static const uint16_t ci18n_en_seeds[] CI18N_ROM = {
    1, 1, 0, 0,
};

static const ci18n_compiled_t ci18n_compiled_en = {
    CI18N_COMPILED_FORMAT, 4, 7, 3,
    ci18n_en_strings, ci18n_en_entries, ci18n_en_slots, ci18n_en_seeds
};

#endif
