#!/usr/bin/env python3
"""
Generate tests/cldr_samples.h from the CLDR plural data.

CLDR publishes, next to every plural rule, sample numbers that fall under it.
This turns those samples into a table the unit tests walk, so the library's
plural and ordinal rules are checked against the published data rather than
against anyone's memory of it. Eight languages had wrong cardinal rules until
this check existed: Hebrew, Marathi and Sinhala, and the whole-million form in
French, Portuguese, Spanish, Italian and Catalan.

    python3 tools/cldr_samples.py            # fetch the pinned CLDR release
    python3 tools/cldr_samples.py --data DIR # use plurals.json and ordinals.json in DIR

When CLDR releases, bump CLDR_VERSION, rerun, and read the diff: a changed
sample means a changed rule, which needs a matching change in ci18n.h.

SPDX-License-Identifier: MIT
"""
import argparse
import json
import os
import re
import sys
import urllib.request

CLDR_VERSION = '48.0.0'
URL = ('https://raw.githubusercontent.com/unicode-org/cldr-json/%s/'
       'cldr-json/cldr-core/supplemental/%s.json')

HERE = os.path.dirname(os.path.abspath(__file__))
HEADER = os.path.join(HERE, '..', 'include', 'ci18n.h')
OUT = os.path.join(HERE, '..', 'tests', 'cldr_samples.h')

ORDER = ['zero', 'one', 'two', 'few', 'many', 'other']

# Every sample is kept, ranges included. CLDR picks them to cover each
# clause of a rule, and any trimming loses exactly the interesting ones: a
# cap per category dropped Azerbaijani's 100, and keeping only the ends of
# a range dropped the English 12, both of which the tests then missed.

# Pre-1989 codes the library accepts, which CLDR files under their current
# names. Without this they would look like languages with no plural forms.
ALIASES = {'iw': 'he', 'ji': 'yi', 'in': 'id'}


def fetch(name, data_dir):
    if data_dir:
        with open(os.path.join(data_dir, name + '.json'), encoding='utf-8') as f:
            return json.load(f)
    with urllib.request.urlopen(URL % (CLDR_VERSION, name)) as r:
        return json.loads(r.read().decode('utf-8'))


def supported_languages():
    """The languages the library claims, read from its own cardinal table."""
    with open(HEADER, encoding='utf-8') as f:
        text = f.read()
    return sorted(set(re.findall(r'\{"([a-z]{2,3})", CI18N_PF_[A-Z_]+\}', text)))


def integer_samples(rule):
    """Every @integer sample of one rule, ranges expanded, ellipsis dropped."""
    m = re.search(r'@integer([^@]*)', rule)
    if not m:
        return []
    values = []
    for part in m.group(1).split(','):
        part = part.strip().rstrip('…').strip()
        if not part:
            continue
        # Compact notation such as 1c6 exercises the exponent operand, which
        # only matters for "1M" style display. The library counts integers.
        if 'c' in part or 'e' in part:
            continue
        if '~' in part:
            lo, hi = (int(x) for x in part.split('~'))
            values.extend(range(lo, hi + 1))
        else:
            values.append(int(part))
    return values


def rows(table, languages, kind):
    out = []
    for lang in languages:
        rules = table.get(ALIASES.get(lang, lang))
        if rules is None:
            # No data for this language: every count is "other", which is
            # also what the library assumes. Record a few to hold it to that.
            for n in (0, 1, 2, 3, 11, 100):
                out.append((lang, n, kind, 'other'))
            continue
        for cat in ORDER:
            rule = rules.get('pluralRule-count-' + cat)
            if rule is None:
                continue
            for n in integer_samples(rule):
                out.append((lang, n, kind, cat))
    return out


def main():
    parser = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    parser.add_argument('--data', help='directory holding plurals.json and ordinals.json')
    args = parser.parse_args()

    cardinal = fetch('plurals', args.data)
    ordinal = fetch('ordinals', args.data)
    version = cardinal['supplemental']['version']['_cldrVersion']

    langs = supported_languages()
    samples = (rows(cardinal['supplemental']['plurals-type-cardinal'], langs, 'CARDINAL') +
               rows(ordinal['supplemental']['plurals-type-ordinal'], langs, 'ORDINAL'))

    lines = [
        '/*',
        ' * Generated by tools/cldr_samples.py from CLDR %s. Do not edit by hand:' % version,
        ' * change the generator or the data, and regenerate.',
        ' *',
        ' * Each row is a count CLDR itself gives as an example of a category, for',
        ' * one of the %d languages the library has rules for.' % len(langs),
        ' *',
        ' * SPDX-License-Identifier: MIT',
        ' */',
        '',
        '#define CI18N_CLDR_SAMPLES_VERSION "%s"' % version,
        '',
        '/* Where the table lives. The rows are read through CLDR_SAMPLE_READ, so',
        ' * a target that keeps constants apart from RAM, such as AVR, can put',
        ' * the table in flash by defining both before including this file. */',
        '#ifndef CLDR_SAMPLES_STORAGE',
        '#define CLDR_SAMPLES_STORAGE',
        '#define CLDR_SAMPLE_READ(dst, src) memcpy((dst), (src), sizeof(*(dst)))',
        '#endif',
        '',
        'typedef enum { CLDR_CARDINAL, CLDR_ORDINAL } cldr_kind_t;',
        '',
        'static const char cldr_languages[][4] = {',
    ]
    for i in range(0, len(langs), 10):
        lines.append('    ' + ' '.join('"%s",' % l for l in langs[i:i + 10]))
    lines += [
        '};',
        '',
        '/* Seven bytes a row, so the table stays under the 32 KB a single object',
        ' * may take where size_t is 16 bits. */',
        'typedef struct',
        '{',
        '    long count;',
        '    unsigned char language; /* index into cldr_languages */',
        '    unsigned char kind;     /* cldr_kind_t */',
        '    unsigned char category; /* ci18n_plural_category_t */',
        '} cldr_sample_t;',
        '',
        'static const cldr_sample_t cldr_samples[] CLDR_SAMPLES_STORAGE = {',
    ]
    for lang, n, kind, cat in samples:
        lines.append('    {%d, %d, CLDR_%s, CI18N_PLURAL_%s},' % (n, langs.index(lang), kind, cat.upper()))
    lines.append('};')
    lines.append('')

    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))

    print('wrote %s: %d samples, %d languages, CLDR %s'
          % (os.path.relpath(OUT), len(samples), len(langs), version))


if __name__ == '__main__':
    sys.exit(main())
