#!/usr/bin/env python3
"""
Generate the number symbol tables in include/ci18n.h, and the samples in
tests/cldr_numbers.h that the unit tests check them against.

For every language the library has plural rules for, CLDR says which
character separates the decimals, which one groups the thousands, how the
minus sign is written, how many digits a number needs before it is grouped
at all, and whether groups after the first are three digits or two, as in
the Indian 12,34,567. That is all the library takes. Currency, percent,
compact forms and native digits are out of scope, see docs/scope.md.

    python3 tools/cldr_numbers.py            # fetch the pinned CLDR release
    python3 tools/cldr_numbers.py --data DIR # use DIR/<lang>/numbers.json

When CLDR releases, bump CLDR_VERSION, rerun, and read the diff.

SPDX-License-Identifier: MIT
"""
import argparse
import json
import os
import re
import sys
import urllib.request

CLDR_VERSION = '48.0.0'
URL = ('https://raw.githubusercontent.com/unicode-org/cldr-json/%s/'
       'cldr-json/cldr-numbers-full/main/%s/numbers.json')

HERE = os.path.dirname(os.path.abspath(__file__))
HEADER = os.path.join(HERE, '..', 'include', 'ci18n.h')
SAMPLES = os.path.join(HERE, '..', 'tests', 'cldr_numbers.h')

BEGIN = '/* BEGIN generated by tools/cldr_numbers.py, do not edit */\n'
END = '/* END generated by tools/cldr_numbers.py */\n'

# Codes the library accepts that CLDR files under their current names.
ALIASES = {'iw': 'he', 'ji': 'yi', 'in': 'id'}

# What the tests format in every language: grouping thresholds, a sign,
# rounding half to even, and a carry that adds a digit.
CASES = [
    ('1234567.891', -1),
    ('-1234.5', -1),
    ('1234', -1),
    ('12345', -1),
    ('123456789', -1),
    ('0.5', -1),
    ('1234.5678', 2),
    ('-0.125', 2),
    ('999.995', 2),
    ('2.5', 0),
    ('7', 3),
]


def supported_languages():
    """The languages the library claims, read from its own cardinal table."""
    with open(HEADER, encoding='utf-8') as f:
        text = f.read()
    return sorted(set(re.findall(r'\{"([a-z]{2,3})", CI18N_PF_[A-Z_]+\}', text)))


def fetch(code, data_dir):
    if data_dir:
        with open(os.path.join(data_dir, code, 'numbers.json'), encoding='utf-8') as f:
            data = json.load(f)
    else:
        with urllib.request.urlopen(URL % (CLDR_VERSION, code)) as r:
            data = json.loads(r.read().decode('utf-8'))
    return data['main'][code]['numbers']


def shape_of(numbers):
    """(decimal, group, minus, minimum grouping digits, secondary group size)"""
    symbols = numbers['symbols-numberSystem-latn']
    pattern = numbers['decimalFormats-numberSystem-latn']['standard'].split(';')[0]
    integer = pattern.split('.')[0]
    groups = integer.split(',')
    primary = len(groups[-1])
    secondary = len(groups[-2]) if len(groups) > 2 else primary
    if primary != 3:
        raise SystemExit('unexpected primary grouping in %r' % pattern)
    return (symbols['decimal'], symbols['group'], symbols['minusSign'],
            int(numbers.get('minimumGroupingDigits', '1')), secondary)


def c_string(text):
    """A C literal. Non-ASCII goes out as three-digit octal escapes, and the
    literal is split after one that a digit follows: "\\240234" is legal C,
    but MSVC warns about it at /W4, which /WX makes an error."""
    out = []
    escaped = False
    for b in text.encode('utf-8'):
        if b < 0x80 and chr(b) not in '"\\':
            if escaped and chr(b).isdigit():
                out.append('" "')
            out.append(chr(b))
            escaped = False
        else:
            out.append('\\%03o' % b)
            escaped = True
    return '"%s"' % ''.join(out)


def format_number(shape, number, fraction_digits):
    """The reference the C code is tested against."""
    decimal, group, minus, min_grouping, secondary = shape
    negative = number.startswith('-')
    body = number.lstrip('+-')
    integer, _, fraction = body.partition('.')
    integer = integer.lstrip('0')

    if fraction_digits >= 0:
        # Round half to even, as CLDR and ICU do by default.
        tail = (fraction + '0' * fraction_digits)[fraction_digits:]
        digits = list(integer + (fraction + '0' * fraction_digits)[:fraction_digits])
        if tail:
            first, rest = tail[0], tail[1:]
            last_odd = int(digits[-1]) % 2 == 1 if digits else False
            up = first > '5' or (first == '5' and (rest.strip('0') or last_odd))
            if up:
                i = len(digits) - 1
                while i >= 0 and digits[i] == '9':
                    digits[i] = '0'
                    i -= 1
                if i >= 0:
                    digits[i] = str(int(digits[i]) + 1)
                else:
                    digits.insert(0, '1')
        split = len(digits) - fraction_digits
        integer = ''.join(digits[:split])
        fraction = ''.join(digits[split:])

    if not integer:
        integer = '0'

    grouped = integer
    if len(integer) >= 3 + min_grouping:
        parts = [integer[-3:]]
        rest = integer[:-3]
        while rest:
            parts.insert(0, rest[-secondary:])
            rest = rest[:-secondary]
        grouped = group.join(parts)

    if negative and (integer + fraction).strip('0'):
        grouped = minus + grouped
    return grouped + (decimal + fraction if fraction else '')


def main():
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[1])
    parser.add_argument('--data', help='directory with <lang>/numbers.json')
    args = parser.parse_args()

    languages = supported_languages()
    shapes = []
    rows = []
    for lang in languages:
        shape = shape_of(fetch(ALIASES.get(lang, lang), args.data))
        if shape not in shapes:
            shapes.append(shape)
        rows.append((lang, shapes.index(shape)))

    english = shapes[dict(rows)['en']]

    block = [BEGIN,
             '/* CLDR %s, the Latin-digit symbols of each language. */\n' % CLDR_VERSION,
             'static const ci18n_number_shape_t ci18n_number_shapes[] CI18N_ROM = {\n']
    for d, g, m, mg, sec in shapes:
        block.append('    {%s, %s, %s, %d, %d},\n' % (c_string(d), c_string(g), c_string(m), mg, sec))
    block.append('};\n\n')
    block.append('/* Unknown languages take this one, as they take English plurals. */\n')
    block.append('#define CI18N_NUMBER_DEFAULT_SHAPE %d\n\n' % shapes.index(english))
    block.append('static const ci18n_number_language_t ci18n_number_languages[] CI18N_ROM = {\n')
    for i in range(0, len(rows), 6):
        chunk = rows[i:i + 6]
        block.append('    ' + ' '.join('{"%s", %d},' % r for r in chunk) + '\n')
    block.append('};\n')
    block.append(END)

    with open(HEADER, encoding='utf-8', newline='') as f:
        header = f.read()
    crlf = '\r\n' in header
    header = header.replace('\r\n', '\n')
    start = header.index(BEGIN)
    stop = header.index(END) + len(END)
    header = header[:start] + ''.join(block) + header[stop:]
    with open(HEADER, 'w', encoding='utf-8', newline='') as f:
        f.write(header.replace('\n', '\r\n') if crlf else header)

    out = ['/*\n',
           ' * Generated by tools/cldr_numbers.py from CLDR %s. Do not edit.\n' % CLDR_VERSION,
           ' *\n',
           ' * SPDX-License-Identifier: MIT\n',
           ' */\n\n',
           '#define CI18N_CLDR_NUMBERS_VERSION "%s"\n\n' % CLDR_VERSION,
           '/* Where the expected results live. They are read through\n'
           ' * CLDR_NUMBER_READ, so a target that keeps constants apart from RAM,\n'
           ' * such as AVR, can put them in flash by defining both first. */\n'
           '#ifndef CLDR_NUMBERS_STORAGE\n'
           '#define CLDR_NUMBERS_STORAGE\n'
           '#define CLDR_NUMBER_READ(dst, src) memcpy((dst), (src), sizeof(dst))\n'
           '#endif\n\n',
           '/* Every language formats the same inputs. */\n'
           'typedef struct\n{\n    const char *number;\n    int fraction_digits;\n'
           '} cldr_number_input_t;\n\n',
           'static const cldr_number_input_t CLDR_NUMBER_INPUTS[] = {\n']
    for number, digits in CASES:
        out.append('    {"%s", %d},\n' % (number, digits))
    out.append('};\n\n')
    # "xx" is a language CLDR does not have, which takes the default.
    languages_out = [lang for lang, _ in rows] + ['xx']
    expected = [[format_number(shapes[index], number, digits) for number, digits in CASES]
                for _, index in rows]
    expected.append([format_number(english, number, digits) for number, digits in CASES])
    width = max(len(e.encode('utf-8')) for row in expected for e in row) + 1
    out.append('static const char CLDR_NUMBER_LANGUAGES[][4] = {\n')
    for i in range(0, len(languages_out), 10):
        out.append('    ' + ' '.join('"%s",' % l for l in languages_out[i:i + 10]) + '\n')
    out.append('};\n\n')
    out.append('/* What CLDR says each language makes of each input. */\n')
    out.append('static const char CLDR_NUMBER_EXPECTED[][%d][%d] CLDR_NUMBERS_STORAGE = {\n'
               % (len(CASES), width))
    for lang, row in zip(languages_out, expected):
        out.append('    /* %s */ {%s},\n' % (lang, ', '.join(c_string(e) for e in row)))
    out.append('};\n')
    with open(SAMPLES, 'w', encoding='utf-8', newline='\n') as f:
        f.write(''.join(out))

    print('%d languages, %d shapes, %d cases' % (len(rows), len(shapes),
                                                 (len(rows) + 1) * len(CASES)),
          file=sys.stderr)


if __name__ == '__main__':
    main()
